apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  annotations: 
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: engineering-week-helm
spec:
  project: tooling
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets/
    helm:
      releaseName: sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: tooling
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
