apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tooling
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: tooling
  source:
    path: helm
    repoURL: https://github.com/ebdekock/argo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
