apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tooling
  namespace: tooling
spec:
  destination:
    namespace: tooling
    name: tooling
    server: in-cluster
  project: default
  source:
    path: helm
    repoURL: https://github.com/ebdekock/argo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
