apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tooling
  namespace: tooling
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: tooling
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm
    repoURL: https://github.com/ebdekock/argo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
