apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  source:
    targetRevision: v1.9.1
    helm:
      parameters:
        - name: replicaCount
          value: "2"
        - name: installCRDs
          value: "true"
