apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  source:
    targetRevision: v1.9.1
    helm:
      valueFiles:
        - prod/k8s01/tooling/cert-manager-values.yml
