apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: tooling
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.9.1
    helm:
      releaseName: cert-manager
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: tooling
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
