apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/cert-manager
  - ../../base/sealed-secrets

patchesStrategicMerge:
  - cert-manager.yml
  - sealed-secrets.yml

generatorOptions:
  disableNameSuffixHash: true
